### ISSUE TITLE
Exception autoload 问题

### ISSUE THREAD

**Issue by bastengao** [qiniu/ruby-sdk#141]
当我直接调用 `Qiniu.upload_file`  的时候出现  `uninitialized constant Module::MissingArgsError`. 很可能是 autoload 的是 Exception， 但是使用 MissingArgsError 的时候不会触发 autoload. 可以改为 `require 'qiniu/exceptions'`. 版本 '6.5.1'

**Comment by longbai** [comment]
收到，我们看下

**Comment by longbai** [comment]
fixed in #142
