### ISSUE TITLE
应该包含 Gemfile.lock 么？

### ISSUE THREAD

**Issue by francistm** [qiniu/ruby-sdk#143]
记得看过一些 gem 的源码，大家都将 `Gemfile.lock` 添加在 `.gitignore` 中。

参考 [Clarifying the Roles of the .gemspec and Gemfile](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/) 也提到不应该将 `Gemfile.lock` 文件添加至版本控制。

查到 #1 这个 issue，理由是不是有些过于牵强了……

**Comment by longbai** [comment]
我处理下，多谢
