### ISSUE TITLE
配置 access_key 和 secret_key 能不能不是全局的配置

### ISSUE THREAD

**Issue by bastengao** [qiniu/ruby-sdk#154]
如果是全局的配置，我们在一个程序里就没有办法同时使用两个以上的账户了。

**Comment by lilanjun2016** [comment]
默认的是全局的配置，如果您需要多个账户，需要您修改源码。

**Comment by bastengao** [comment]
我再吐槽一次，我有个需求就是要把一个账号的图片迁移到另一个账户去，你们这样子我程序根本没办法写。
