### ISSUE TITLE
stat方法能否不屏幕打印warn吗？

### ISSUE THREAD

**Issue by dongli** [qiniu/ruby-sdk#157]
我用`Qiniu::Storage.stat`方法查看一个文件是否上传，没有上传对我的应用来说也不是错误，但是却会屏幕打印警告，我看了程序[这里](https://github.com/qiniu/ruby-sdk/blob/master/lib/qiniu/http.rb#L93)打印的。能否不打印或者给个选项呢？

**Comment by lilanjun2016** [comment]
粘贴下详细提示看下。
