### ISSUE TITLE
upload_with_token_2方法少了一个参数？

### ISSUE THREAD

**Issue by Zkuns** [qiniu/ruby-sdk#165]
我按照文档中的upload_with_token_2方法写上传测试，会报BucketIsMissing错误，但是bucket_name在生成token的时候就传入了，所以十分奇怪。 后来看了upload_with_token_2方法的代码才发现，调用upload_with_token_2方法时得再传一遍bucket参数，在opts参数中加入就可以了。
所以是不是可以改改rubySDK的文档，调用upload_with_token_2时，加入bucket参数的提示，或者就generate_uptoken就将bucket参数存入Config。

**Comment by lilanjun2016** [comment]
谢谢您的反馈，目前加了。

**Comment by Zkuns** [comment]
谢谢
