### ISSUE TITLE
vframe操作是否有缓存

### ISSUE THREAD

**Issue by happyming9527** [qiniu/ruby-sdk#166]
@longbai @lidaobing @ledowong 我在你们fetch方法的例子中,看到saveas的操作,这个意思是截帧服务是耗时操作,截取之后需要保存,下次直接访问这个保存的截图,以此来加快访问截图的速度么?
请问视频截帧能否像图片一样,通过在视频的访问url后面加上vframe的参数来访问?如果可以的话,这种访问的方式,是否有缓存?还是说每次访问都会去进行耗时的截帧操作?

**Comment by SomeOneToken** [comment]
视频截帧可以直接通过在视频的访问url后面加上vframe的参数来访问,类似http://<bucket>/my.mp4?vframe/jpg/offset/9,也是遇到了视频截图的问题

**Comment by lilanjun2016** [comment]
可以通过预转持久化数据处理或者持久化数据处理的方式来调用Vframe操作，所以它是个异步操作，可以第一次保存在空间。接下来就与其他上传到空间的文件一样的访问了。
