### ISSUE TITLE
Qiniu::Storage.upload_with_token_2 的正确写法修改如下

### ISSUE THREAD

**Issue by lolomarx** [qiniu/ruby-sdk#171]
@bucket = 'bucket01'
code, result, response_headers = Qiniu::Storage.upload_with_token_2(
             uptoken, 
             filePath,
             key,
             nil,
             bucket: @bucket
        )

**Comment by longbai** [comment]
多谢，我们看下

**Comment by lolomarx** [comment]
应该是http://developer.qiniu.com/code/v6/sdk/ruby.html 需要修改，避免其他人又用错了

**Comment by lilanjun2016** [comment]
好的，我们确认下。

**Comment by lilanjun2016** [comment]
这个修改好了。谢谢你。
