### ISSUE TITLE
访问 http://uc.qbox.me 报告 Connection reset by peer

### ISSUE THREAD

**Issue by wppurking** [qiniu/ruby-sdk#177]
https://github.com/qiniu/ruby-sdk/blob/master/lib/qiniu/host_manager.rb#L69

在检查可用的 hosts 的时候访问的是 http 的请求, 但是通过 curl 来测试获取 hosts 的 api 的时候已经进行了 connection reset , 猜测和最近的全站 https 有关, 但 sdk 中并没有进行更新.

SDK 中默认使用的 http
![image](https://cloud.githubusercontent.com/assets/448364/21347089/2118382a-c6e2-11e6-9d68-8c902ea0f8b1.png)

使用 https 的有情况
![image](https://cloud.githubusercontent.com/assets/448364/21347124/4f9b7446-c6e2-11e6-834c-f9ae629e1b55.png)

使用时的 WARN 日志
![image](https://cloud.githubusercontent.com/assets/448364/21347174/7499324c-c6e2-11e6-8968-ab0080dcb410.png)

在 https://github.com/qiniu/ruby-sdk/blob/master/lib/qiniu/config.rb 中有很多 url 相关参数, 并不确定是否都需要改为 https. 多数 API 用户本身不会使用到, 所以无法测试更多.

**Comment by wppurking** [comment]
@longbai 如果用户手动指定上传的路径则可以使用.  这个是否可以及时跟进一下 https 的变动?

**Comment by lilanjun2016** [comment]
目前是由于域名的问题，.qbox.me  域名，需要使用https的方式，抱歉啦
