### ISSUE TITLE
上传图片时参数警告wrong number of arguments (given 1, expected 0) => Qiniu::HTTP.post('http://up.qiniu.com/')，上传不成功

### ISSUE THREAD

**Issue by lioncruise** [qiniu/ruby-sdk#180]
D, [2016-12-29T09:38:08.141462 #6807] DEBUG -- : Query qinshijun hosts Success: {"ttl"=>86400, "http"=>{"io"=>["http://iovip.qbox.me"], "up"=>["http://up.qiniu.com", "http://upload.qiniu.com", "-H up.qiniu.com http://183.136.139.16"]}, "https"=>{"io"=>["https://iovip.qbox.me"], "up"=>["https://up.qbox.me"]}}

W, [2016-12-29T09:38:08.144171 #6807]  WARN -- : wrong number of arguments (given 1, expected 0) => Qiniu::HTTP.post('http://up.qiniu.com/')

#打印上传返回的信息
puts code.inspect                    
puts result.inspect
puts response_headers.inspect

结果为：
0
{}
{}

完全按照Ruby SDK官方文档的上传步骤书写，上传图片不成功。SDK版本6.8.1。

**Comment by lilanjun2016** [comment]
具体你提供下哪些参数。
wrong number of arguments @lioncruise
