### ISSUE TITLE
依赖 gem json 不需要 lock 版本吧， 在项目中与其它 json 版本有冲突

### ISSUE THREAD

**Issue by songjiayang** [qiniu/ruby-sdk#192]
https://github.com/qiniu/ruby-sdk/blob/master/qiniu.gemspec#L24

**Comment by wppurking** [comment]
这个在 #167 中解决并且 merge 了, 并且 v6.8.1 已经是 `json >= 1.8` 了不知道为什么 master 分支又回去了. 

相关的 issue 还有 #183 

@longbai 给这个项目一点关注吧, 已经看到 3 个 fork 都是 commit 解决 json 依赖的问题.

然后, rubygems.org 上的版本也是还是 v6.8.1  虽然 master 已经到 6.9.0 了.

https://rubygems.org/gems/qiniu/versions
![image](https://cloud.githubusercontent.com/assets/448364/23780429/e481b664-0581-11e7-9dba-3ced6ff55728.png)

**Comment by songjiayang** [comment]
原来没有 push 到 rubygems...
