### ISSUE TITLE
服务端上传图片，好多出现图片不完整的情况

### ISSUE THREAD

**Issue by ryancheung** [qiniu/ruby-sdk#197]
http://static.woqi.me/tshirt/image/26137/meitu_1492219648884_old.png

我用的是 gem paperclip-qiniu

**Comment by songjiayang** [comment]
请问原始文件大小是，有可能断点续传问题

**Comment by songjiayang** [comment]
paperclip-qiniu 很久没升级了，依赖的 ruby-sdk 也较老，升级试试？

**Comment by ryancheung** [comment]
@songjiayang 升级到 6.8.1 后，依然会出现图片不完整的错误 http://static.woqi.me/tshirt/image/27160/meitu_1495792472812.png

**Comment by ryancheung** [comment]
为什么关闭啊

**Comment by songjiayang** [comment]
@ryancheung 应该要重新开，然后统一维护
