### ISSUE TITLE
rails5不兼容

### ISSUE THREAD

**Issue by hyacinthxinxin** [qiniu/ruby-sdk#209]
Bundler could not find compatible versions for gem "mime-types":
  In snapshot (Gemfile.lock):
    mime-types (= 3.1)

  In Gemfile:

    rails_admin (~> 1.1.1) was resolved to 1.1.1, which depends on
      rails (< 6, >= 4.0) was resolved to 5.0.1, which depends on
        actionmailer (= 5.0.1) was resolved to 5.0.1, which depends on
          mail (>= 2.5.4, ~> 2.5) was resolved to 2.6.4, which depends on
            mime-types (< 4, >= 1.16)

    qiniu (>= 6.8.1, ~> 6.8) was resolved to 6.8.1, which depends on
      mime-types (>= 2.4.0, ~> 2.4)

**Comment by 1c7** [comment]
叹气，官方文档里说6.9 ，6.9 也装不了，然后 6.8 也是碰到和你一样的问题，我在用 Rails 5.1.2

**Comment by 1c7** [comment]
try `bundle update`, it works for me
##Before
![image](https://user-images.githubusercontent.com/1804755/30998381-ab8b198e-a493-11e7-87b4-a7536e33da47.png)

## After
![image](https://user-images.githubusercontent.com/1804755/30998348-72cdae5e-a493-11e7-9899-93d4a90895a7.png)

**Comment by jicheng1014** [comment]
@1c7    https://rubygems.org/gems/qiniu       七牛没推6.9 的 gem 到rubygems

**Comment by 1c7** [comment]
@jicheng1014 ok 多谢回复，问题早就解决了，只是比较烦心文档不一致的问题。没有推 6.9 就不要写嘛。。

**Comment by songjiayang** [comment]
Hi guys, `qiniu` 6.9 push to RubyGems now.
